#!/usr/bin/env node
// build-embed.js — Reads the agent's dashboard-data.json and active-prs.json,
// transforms raw ADO items into lean JS constants for team-dashboard.html.
//
// Usage:  node build-embed.js
// Output: data-embed.js (inline into the HTML's <script> block)

const fs = require('fs');
const path = require('path');

const SYNC_DIR = path.join(
  process.env.OneDrive || process.env.USERPROFILE || process.env.HOME,
  'Documents', 'agent-sync');

const dashPath = path.join(SYNC_DIR, 'dashboard-data.json');
const prPath   = path.join(SYNC_DIR, 'active-prs.json');

if (!fs.existsSync(dashPath)) { console.error(`Missing: ${dashPath}`); process.exit(1); }
if (!fs.existsSync(prPath))   { console.error(`Missing: ${prPath}`); process.exit(1); }

const dash = JSON.parse(fs.readFileSync(dashPath, 'utf8'));
const prs  = JSON.parse(fs.readFileSync(prPath, 'utf8'));

const now = new Date();
function daysBetween(d1, d2) { return Math.round((d2 - d1) / 864e5); }

function transformItem(raw) {
  const f = raw.fields;
  const assignedObj = f['System.AssignedTo'];
  const assigned = (typeof assignedObj === 'object' && assignedObj)
    ? assignedObj.displayName
    : (assignedObj || '');

  const created      = f['System.CreatedDate'] ? new Date(f['System.CreatedDate']) : null;
  const activated    = f['Microsoft.VSTS.Common.ActivatedDate'] ? new Date(f['Microsoft.VSTS.Common.ActivatedDate']) : null;
  const stateChanged = f['Microsoft.VSTS.Common.StateChangeDate'] ? new Date(f['Microsoft.VSTS.Common.StateChangeDate']) : null;

  // PR links from ArtifactLink relations
  const prLinks = (raw.relations || [])
    .filter(r => r.rel === 'ArtifactLink' && r.attributes?.name === 'Pull Request')
    .map(r => {
      const match = r.url?.match(/%2F(\d+)$/i) || r.url?.match(/\/(\d+)$/);
      const prId = match ? match[1] : null;
      return {
        name: `PR #${prId || '?'}`,
        url: prId
          ? `https://dev.azure.com/{your-org}/{your-project}/_git/{your-repo}/pullrequest/${prId}`
          : r.url,
        id: prId ? parseInt(prId) : null
      };
    });

  // Child IDs from forward hierarchy links
  const childIds = (raw.relations || [])
    .filter(r => r.rel === 'System.LinkTypes.Hierarchy-Forward')
    .map(r => { const m = r.url?.match(/\/(\d+)$/); return m ? parseInt(m[1]) : null; })
    .filter(Boolean);

  const state = f['System.State'];
  const closed = f['Microsoft.VSTS.Common.ClosedDate'] ? new Date(f['Microsoft.VSTS.Common.ClosedDate']) : null;
  const resolved = f['Microsoft.VSTS.Common.ResolvedDate'] ? new Date(f['Microsoft.VSTS.Common.ResolvedDate']) : null;
  const endDate = closed || resolved;
  const ageTarget = (state === 'Closed' || state === 'Resolved') && endDate ? endDate : now;

  const item = {
    id: raw.id,
    type: f['System.WorkItemType'],
    state,
    priority: f['Microsoft.VSTS.Common.Priority'],
    title: f['System.Title'],
    tags: f['System.Tags'] || '',
    assigned,
    parent: f['System.Parent'] || null,
    iteration: f['System.IterationPath'] || '',
    storyPoints: f['Microsoft.VSTS.Scheduling.StoryPoints'] || null,
    prCount: prLinks.length,
    age: {
      sinceCreated:     created      ? daysBetween(created, ageTarget)      : null,
      sinceActivated:   activated    ? daysBetween(activated, ageTarget)    : null,
      sinceStateChange: stateChanged ? daysBetween(stateChanged, now)       : null,
      sinceAssigned:    activated    ? daysBetween(activated, ageTarget)    : null,
      cycleTime:        (closed || resolved) && activated ? daysBetween(activated, endDate) : null
    }
  };

  if (prLinks.length)  item.linkedPRs = prLinks;
  if (childIds.length) item.childIds  = childIds;
  return item;
}

// --- Transform ---
const items = dash.sprints.current.items.map(transformItem);

const sprintData = {
  name:  dash.sprints.current.name,
  start: dash.sprints.current.startDate,
  end:   dash.sprints.current.endDate,
  days:  daysBetween(new Date(dash.sprints.current.startDate), new Date(dash.sprints.current.endDate)) + 1
};

// Velocity from previous sprint (same shape as old VELOCITY_PREV_SPRINT_PTS)
const velocityPrev = {};
if (dash.velocity?.previous?.byPerson) {
  for (const [name, v] of Object.entries(dash.velocity.previous.byPerson)) {
    velocityPrev[name] = { points: v.points || 0, items: v.items || 0 };
  }
}

// Active PRs — keep lean
const activePrs = prs.map(p => ({
  prId:         p.prId,
  repo:         p.repository,
  url:          p.url,
  title:        p.title,
  status:       p.status,
  createdBy:    p.createdBy,
  createdDate:  p.createdDate,
  sourceBranch: (p.sourceRefName || '').replace('refs/heads/', ''),
  targetBranch: (p.targetRefName || '').replace('refs/heads/', '')
}));

// --- Output ---
const output = [
  `// Auto-generated by build-embed.js — ${now.toISOString()}`,
  `// Source: ${items.length} current-sprint items, ${activePrs.length} active PRs`,
  `const GENERATED_AT = ${JSON.stringify(dash.generated)};`,
  `const SPRINT_DATA = ${JSON.stringify(sprintData)};`,
  `const VELOCITY_PREV = ${JSON.stringify(velocityPrev)};`,
  `const EMBED_ITEMS = ${JSON.stringify(items)};`,
  `const ACTIVE_PRS = ${JSON.stringify(activePrs)};`,
].join('\n');

const outPath = path.join(__dirname, 'data-embed.js');
fs.writeFileSync(outPath, output, 'utf8');

const kb = (s) => (Buffer.byteLength(s, 'utf8') / 1024).toFixed(1);
console.log(`✓ ${outPath}`);
console.log(`  ${items.length} items (${kb(JSON.stringify(items))}KB)`);
console.log(`  ${activePrs.length} PRs (${kb(JSON.stringify(activePrs))}KB)`);
console.log(`  Total: ${kb(output)}KB`);
